import { ReactComponent as GridView } from '../icons/gridd-md.svg';
import { ReactComponent as SingleView } from '../icons/single-md.svg';
import { ReactComponent as PIPView } from '../icons/pip-md.svg';
import { ReactComponent as SpeakerView } from '../icons/speaker-md.svg';
import { ReactComponent as SplitView } from '../icons/split-md.svg';
import { PositionEdge, PositionCorner } from './positions';
import { Param } from '../types/params';

export const viewParams: Param[] = [
  {
    id: 'mode',
    label: 'Mode',
    type: 'menu',
    defaultValue: 'grid',
    menu: [
      { label: 'Single', value: 'single', icon: SingleView },
      { label: 'Split', value: 'split', icon: SplitView },
      { label: 'Grid', value: 'grid', icon: GridView },
      { label: 'Speaker', value: 'dominant', icon: SpeakerView },
      { label: 'PIP', value: 'pip', icon: PIPView },
    ],
  },
  {
    id: 'videoSettings.dominant.position',
    label: 'Active Speaker Position',
    type: 'enum',
    defaultValue: PositionEdge.LEFT,
    values: Object.values(PositionEdge),
    render: { key: 'mode', value: 'dominant' },
  },
  {
    id: 'videoSettings.dominant.splitPos',
    label: 'Active Speaker Width',
    type: 'range',
    defaultValue: 0.8,
    step: 0.1,
    min: 0,
    max: 1,
    render: { key: 'mode', value: 'dominant' },
  },
  {
    id: 'videoSettings.dominant.numChiclets',
    label: 'Number of tiles to display (except active speaker)',
    type: 'number',
    defaultValue: 5,
    render: { key: 'mode', value: 'dominant' },
  },
  {
    id: 'videoSettings.dominant.followDomFlag',
    label: 'Follow active speaker',
    type: 'boolean',
    defaultValue: true,
    render: { key: 'mode', value: 'dominant' },
  },
  {
    id: 'videoSettings.pip.position',
    label: 'Picture in Picture position',
    type: 'enum',
    defaultValue: PositionCorner.TOP_RIGHT,
    values: Object.values(PositionCorner),
    render: { key: 'mode', value: 'pip' },
  },
  {
    id: 'videoSettings.pip.height_vh',
    label: 'Height of the Picture in Picture',
    type: 'number',
    defaultValue: 0.3,
    step: 0.1,
    min: 0,
    max: 1,
    render: { key: 'mode', value: 'pip' },
  },
  {
    id: 'videoSettings.pip.margin_vh',
    label: 'Margin around the Picture in Picture layout',
    type: 'number',
    defaultValue: 0.04,
    step: 0.01,
    min: 0,
    max: 0.1,
    render: { key: 'mode', value: 'pip' },
  },
  {
    id: 'videoSettings.pip.aspectRatio',
    label: 'PIP Aspect ratio',
    type: 'range',
    defaultValue: 1,
    step: 0.1,
    min: 0,
    max: 1,
    render: { key: 'mode', value: 'pip' },
  },
  {
    id: 'videoSettings.pip.followDomFlag',
    label: 'Follow active speaker',
    type: 'boolean',
    defaultValue: false,
    render: { key: 'mode', value: 'pip' },
  },
  {
    id: 'showParticipantLabels',
    label: 'Show Participant Labels?',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'videoSettings.roundedCorners',
    label: 'Round Corners',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'videoSettings.scaleMode',
    label: 'Scale Mode',
    type: 'enum',
    defaultValue: 'fill',
    values: ['fill', 'fit'],
  },
  {
    id: 'videoSettings.labels.fontFamily',
    label: 'Participant Label Font Family',
    type: 'enum',
    defaultValue: 'Roboto',
    values: [
      'Roboto',
      'RobotoCondensed',
      'Bitter',
      'Exo',
      'Magra',
      'SuezOne',
      'Teko',
    ],
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.labels.fontWeight',
    label: 'Participant Label Font Weight',
    type: 'enum',
    defaultValue: '600',
    values: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.labels.fontSize_pct',
    label: 'Participant Label Font Size',
    type: 'number',
    defaultValue: 100,
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.labels.offset_x',
    label: 'Participant Label Offset X',
    type: 'number',
    defaultValue: 0,
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.labels.offset_y',
    label: 'Participant Label Offset Y',
    type: 'number',
    defaultValue: 0,
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.labels.color',
    label: 'Participant Label Text Color',
    type: 'color',
    defaultValue: '#fff',
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.labels.strokeColor',
    label: 'Participant Label Stroke Color',
    type: 'color',
    defaultValue: 'rgba(0, 0, 0, 0.9)',
    render: { key: 'showParticipantLabels', value: true },
  },
  {
    id: 'videoSettings.margin.left_vw',
    label: 'Video Margin Left',
    type: 'number',
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    id: 'videoSettings.margin.right_vw',
    label: 'Video Margin Right',
    type: 'number',
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    id: 'videoSettings.margin.top_vh',
    label: 'Video Margin Top',
    type: 'number',
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    id: 'videoSettings.margin.bottom_vh',
    label: 'Video Margin Bottom',
    type: 'number',
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
  },
];
